deploymentcalendar: raise on Phabricator error
When one does not have a conduit token set, Phabricator returns a json
formatted error with a 200 status cause. requests response
raise_for_status() thus does not raise.

When Phabricator response has an 'error_code', raise an exception and
dump the message. Example:

Exception: Phabricator API error ERR-INVALID-SESSION: Session key is not present.

Change-Id: I9d77d72bdafe6c76f0f48cbcda7a2200d5ba09ad